FROM centos:7
LABEL maintainer="vmzcloud"

ENV TZ="Asia/Hong_Kong"
ENV TOMCAT_URL="https://dlcdn.apache.org/tomcat/tomcat-8/v8.5.82/bin/apache-tomcat-8.5.82.tar.gz"
ENV JDK_URL="https://github.com/adoptium/temurin11-binaries/releases/download/jdk-11.0.16%2B8/OpenJDK11U-jdk_x64_linux_hotspot_11.0.16_8.tar.gz"

RUN yum -y --setopt=tsflags=nodocs install wget
RUN yum clean all

RUN mkdir /opt/tomcat/
RUN mkdir /opt/JDK

WORKDIR /opt/tomcat
RUN wget --no-check-certificate $TOMCAT_URL
RUN tar xvfz apache*.tar.gz
RUN mv apache-tomcat-*/* /opt/tomcat/.
RUN rm -rf apache*.tar.gz

WORKDIR /opt/JDK
RUN wget --no-check-certificate $JDK_URL
RUN tar xvfz OpenJDK*.tar.gz
RUN mv jdk-*/* /opt/JDK/.
RUN rm -rf OpenJDK*.tar.gz
RUN rm -rf jdk-*

EXPOSE 8080

ENV JAVA_HOME=/opt/JDK
WORKDIR /opt/tomcat/

CMD ["/opt/tomcat/bin/catalina.sh", "run"]
